# Generated by Django 2.2 on 2020-08-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_membership_stripe_subscription_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrequest',
            name='usage_record_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
